export enum BUTTON_TYPE {
  COLORFULL = 'COLORFULL',
  PRIMARY = 'PRIMARY',
  SECONDARY = 'SECONDARY',
  DANGER = 'DANGER',
  SUBSCRIBE = 'SUBSCRIBE',
  LIGHT_GREEN = 'LIGHT_GREEN',
  VIEW = 'VIEW',
}

export enum INPUT_TYPE {
  SEARCH = 'SEARCH',
  BASIC = 'BASIC',
  CHECKBOX = 'CHECKBOX',
  RADIO = 'RADIO',
}

export enum MODAL_TYPE {
  SUBSCRIBE = 'SUBSCRIBE',
}
